# Generated by Django 5.0.6 on 2024-07-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talents',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='reditprof.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='user_bio',
            field=models.TextField(null=True),
        ),
    ]
