# Generated by Django 5.0.6 on 2024-06-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_category_talents_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='talents',
            field=models.ManyToManyField(blank=True, related_name='users', to='base.talents'),
        ),
    ]
