# Generated by Django 5.0.6 on 2024-07-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_user_talents'),
    ]

    operations = [
        migrations.AddField(
            model_name='talents',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='talents',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
